name: Upload Python Package
on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Publish to PyPI
        run: |
          pipx install poetry
          bash ./bin/publish-pypi
        env:
          PYPI_TOKEN: ${{ secrets.MERGE_PYPI_TOKEN }}